language: java

jdk:
- openjdk7

node_js:
- 4.8.3
install: true

cache:
  directories:
  - $HOME/.m2

before_install:
  #- sudo -E apt-get -yq --no-install-suggests --no-install-recommends install oracle-java7-installer
  - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
  - . $HOME/.nvm/nvm.sh
  - nvm install v7.7.1
  - nvm ls
  - nvm use 7
  - npm install -g bower
  - node -v
  - npm -v
  - bower -v

script: mvn clean install -DskipTests=true # Ignore tests bc doclets does not compile with openJDK7.
